export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_START = 'SIGN_IN_START';
export const SIGN_IN_SUCCEED = 'SIGN_IN_SUCCEED';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';

export const SIGN_OUT = 'SIGN_OUT';

export const GET_PROJECTS = 'GET_PROJECTS';
export const GET_PROJECTS_START = 'GET_PROJECTS_START';
export const GET_PROJECTS_SUCCEED = 'GET_PROJECTS_SUCCEED';
export const GET_PROJECTS_FAILED = 'GET_PROJECTS_FAILED';

export const GET_SPECIFIC_PROJECT = 'GET_SPECIFIC_PROJECT';
export const GET_SPECIFIC_PROJECT_START = 'GET_SPECIFIC_PROJECT_START';
export const GET_SPECIFIC_PROJECT_SUCCEED = 'GET_SPECIFIC_PROJECT_SUCCEED';
export const GET_SPECIFIC_PROJECT_FAILED = 'GET_SPECIFIC_PROJECT_FAILED';

export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const UPDATE_PROJECT_START = 'UPDATE_PROJECT_START';
export const UPDATE_PROJECT_SUCCEED = 'UPDATE_PROJECT_SUCCEED';
export const UPDATE_PROJECT_CLEAR = 'UPDATE_PROJECT_CLEAR';
export const UPDATE_PROJECT_FAILED = 'UPDATE_PROJECT_FAILED';
